apiVersion: v1
kind: Service
metadata:
  labels:
    app: to-do-svc
  name: to-do-svc
  namespace: paul-brilmayer
spec:
  clusterIP: 10.245.232.23
  clusterIPs:
    - 10.245.232.23
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 8080-80
      nodePort: 32689
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: to-do-deploy
  sessionAffinity: None
  type: NodePort