name: Deploy Kubernetes

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Create namespace
        run: kubectl create namespace paul-brilmayer --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: 'paul-brilmayer'
          secret-name: 'regcred'
          container-registry-url: 'ghcr.io'
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        id: create-secret